### ISSUE TITLE
"No accept header receieved on handshake response" error after Chrome update

### ISSUE THREAD

**Issue by DenisSokoloff** [chrome-php/headless-chromium-php#492]
Got error after google chrome update at Ubuntu

Google Chrome 111.0.5563.64

Fatal error: Uncaught Wrench\Exception\HandshakeException: No accept header receieved on handshake response in /vendor/chrome-php/wrench/src/Protocol/Protocol.php:469 Stack trace: #0 /vendor/chrome-php/wrench/src/Client.php(243): Wrench\Protocol\Protocol->validateResponseHandshake('HTTP/1.1 403 Fo...', 'BybBKmvy1lqHolj...') https://github.com/chrome-php/chrome/issues/1 /vendor/chrome-php/chrome/src/Communication/Socket/Wrench.php(99): Wrench\Client->connect() https://github.com/chrome-php/chrome/issues/2 /vendor/chrome-php/chrome/src/Communication/Connection.php(186): HeadlessChromium\Communication\Socket\Wrench->connect() https://github.com/chrome-php/chrome/pull/3 /vendor/chrome-php/chrome/src/Browser/BrowserProcess.php(146): HeadlessChromium\Communication\Connection->connect() https://github.com/chrome-php/chrome/issues/4 /vendor/chrome-php/chrome/src/BrowserFactory.php(81): HeadlessChromium in /vendor/chrome-php/wrench/src/Protocol/Protocol.php on line 469

I have updated Chrome for windows (Version 111.0.5563.65 (Official Build) (64-bit)) and got this error too

**Comment by DenisSokoloff** [comment]
Problem with new version of Chrome, 
because I downgrade to previous version Version: **110.0.5481.177-1 | 2023-02-22 19:08:36 UTC**
and with old version - OK!

**Comment by codes-begin** [comment]
Hi Denis, I have started facing this issue since 02:00 IST. How ever I am not able to install older version of chrome using WHM Terminal. Can you please help me out here.

**Comment by MatG01** [comment]
I had the same problem, and could solve it by just copying /opt/google/chrome from a backup. Of course, that's just a quick fix, I hope not to be stuck with this Chrome version for ever.

**Comment by kolinger** [comment]
For .deb based linuxes there is easy fix by downgrading to previous version (110.0.5481.177-1):

Download and install previous version from google repository:
```
wget http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_110.0.5481.177-1_amd64.deb
dpkg -i google-chrome-stable_110.0.5481.177-1_amd64.deb
```

To prevent accidental upgrade until issue is resolved:
```
apt-mark hold google-chrome-stable
```

When you want to upgrade again:
```
apt-mark unhold google-chrome-stable
```

**Comment by DenisSokoloff** [comment]
> Downgraded Versions: https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable

**Comment by codes-begin** [comment]
> > 
> 
> Downgraded Versions: https://www.ubuntuupdates.org/package/google_chrome/stable/main/base/google-chrome-stable

Actually I am using CentOS 7 VPS.

**Comment by GrahamCampbell** [comment]
Are you able to propose a fix please?

**Comment by santossoares** [comment]
@palarvind
For rpm, here is the url:
https://dl.google.com/linux/direct/google-chrome-stable-110.0.5481.177-1.x86_64.rpm

**Comment by santossoares** [comment]
@kolinger 
On CentOS, how to prevent the package from being updated automatically?

**Comment by enaumchuk** [comment]
@santossoares rpm for google chrome is not available
this URL returns 404
https://dl.google.com/linux/direct/google-chrome-stable-110.0.5481.177-1.x86_64.rpm

**Comment by dacodmagagula** [comment]
> @santossoares try [https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-110.0.5481.177-1.x86_64.rpm](https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-110.0.5481.177-1.x86_64.rpm)

**Comment by codes-begin** [comment]
Thanks @dacodmagagula for a working url. Do anyone here aware on how to stop chrome from auto update in case of rpm.

**Comment by DenisSokoloff** [comment]
If anybody needs to downgrade to portable chromium, you can get chromium from https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html

I download portable version on Windows and connect to old version for work, but have last Chrome for web surfing.

**Comment by HayriCan** [comment]
I installed older version and right now i am getting different error.
`Chrome process stopped before startup completed. Additional info: [10772:10772:0311/175922.664633:ERROR:ozone_platform_x11.cc(238)] Missing X server or $DISPLAY [10772:10772:0311/175922.664684:ERROR:env.cc(255)] The platform failed to initialize. Exiting. `

**Comment by GrahamCampbell** [comment]
It looks like this is being caused by a breaking change in Chrome. The response I am getting back, having just tried this out, is:

```
HTTP/1.1 403 Forbidden
Content-Length:229
Content-Type:text/html


Rejected an incoming WebSocket connection from the http://127.0.0.1 origin. Use the command line flag --remote-allow-origins=http://127.0.0.1 to allow connections from this origin or --remote-allow-origins=* to allow all origins.
```

**Comment by GrahamCampbell** [comment]
This issue has been resolved in v1.8.1.

**Comment by audas** [comment]
Updated to 1.9, PHP 8.1 this error is still occurring on windows.

Requires allow remote origins flags to be set.

 $browserFactory->addOptions(['customFlags' => ['--remote-allow-origins=*']]);

Edit: seems I can no longer set options direction on the createBrowser functions which I was doing previously and these must be set explicitly with addOptions

So this no longer works.
 $browser = $browserFactory->createBrowser(['windowSize'   => [$_POST['width'], $_POST['height']]]);

**Comment by madxion** [comment]
this problem is still exist, I am running on Windows 10, Laragon, Php 8.2
